/*
This list of comma-separated decimal ASCII values represents the most
frequent characters in English text, ordered approximately from most to
least frequent.  It includes space, lowercase and uppercase letters, common
punctuation, and numbers 0-9.  This list was generated by ChatGPT, a large
language model from OpenAI, using the following prompt:

"Output a comma-separated list of the decimal ASCII values for the most
frequent characters in English text, ordered approximately from most to
least frequent. Include space, letters (lowercase and uppercase), common punctuation,
and numbers 0-9.  Do *not* include the characters themselves, just the
decimal ASCII values."

It's important to note that the exact frequency order can vary depending on
the specific text analyzed.  This list provides a general approximation.

This list can be used as a basis for text compression algorithms, as
characters with lower ASCII values tend to be more frequent.
*/
static unsigned char table[256] = { 32,101,116,97,111,105,110,115,114,104,108,100,99,117,109,119,102,112,103,121,98,118,107,120,106,113,122,39,44,46,34,63,33,59,58,45,69,84,65,79,73,78,83,82,72,76,68,67,85,77,87,70,80,71,89,66,86,75,88,74,81,90,48,49,50,51,52,53,54,55,56,57, };
